spring.application.name=Ecommerce

spring.h2.console.enabled=true

spring.datasource.url=jdbc:h2:mem:test

spring.jpa.hibernate.ddl-auto=create

app.admin.password=${ADMIN_PASSWORD}

# JWT Configuration
jwt.secret=${JWT_SECRET_KEY}
jwt.expiration-ms=${JWT_EXPITATION_MS}





